# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates#supported-repositories-and-ecosystems
version: 2
updates:
  - package-ecosystem: cargo
    directory: '/'
    schedule:
      interval: daily
      time: "22:00"
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
